param(
    [Parameter(Mandatory = $true)]
    [string] $RootPath,
    [string] $OutputFile = ""
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($OutputFile)) {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $OutputFile = Join-Path (Join-Path $scriptDir "..\mql4\Include") "SYSTEM_RootConfig.mqh"
}

$resolved = [System.IO.Path]::GetFullPath($RootPath).TrimEnd('\')
$escaped = $resolved.Replace('\', '\\')

$content = @"
#ifndef __SYSTEM_ROOT_CONFIG_MQH__
#define __SYSTEM_ROOT_CONFIG_MQH__

// Auto-generated by scripts/generate_mql4_root.ps1 — do not edit by hand.
#define SYSTEM_ROOT_PATH "$escaped"

#endif
"@

Set-Content -LiteralPath $OutputFile -Value $content -Encoding ASCII
Write-Host "MT4 root config: $resolved"
Write-Host "Written: $OutputFile"
