#ifndef __SYSTEM_ROOT_CONFIG_MQH__
#define __SYSTEM_ROOT_CONFIG_MQH__

// Auto-generated by scripts/generate_mql4_root.ps1 during setup.
// Default below is used until setup runs; EA input SystemRootPath can override at runtime.
#define SYSTEM_ROOT_PATH "C:\\SYSTEM"

#endif
